services:
    code-forge:
        image: code-forge
        container_name: code-forge
        ports:
            - 5000:3000
        restart: unless-stopped
        depends_on:
            - redis
        networks:
            - app
      

    redis:
        image: redis:8.4.1-alpine
        container_name: redis-queue
        ports:
            - 6379:6379
        restart: unless-stopped

networks:
    app:
